In [146]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [147]:
# reading data
data = pd.read_csv(r'/Users/freddy/Desktop/CSV_FILES/diabetes.csv')

In [148]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [149]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [150]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [151]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [152]:
# normalizing data


# max
# a1 = d[['Pregnancies']].max()
# a2 = d[['Glucose']].max()
# a3 = d[['BloodPressure']].max()
# a4 = d[['SkinThickness']].max()
# a5 = d[['Insulin']].max()
# a6 = d[['BMI']].max()
# a7 = d[['DiabetesPedigreeFunction']].max()
# a8 = d[['Age']].max()

# #mean
# b1 = d[['Pregnancies']].mean()
# b2 = d[['Glucose']].mean()
# b3 = d[['BloodPressure']].mean()
# b4 = d[['SkinThickness']].mean()
# b5 = d[['Insulin']].mean()
# b6 = d[['BMI']].mean()
# b7 = d[['DiabetesPedigreeFunction']].mean()
# b8 = d[['Age']].mean()

# # scaling (value - mean)/max
# d[['Pregnancies']]=(d[['Pregnancies']]-b1)/a1
# d[['Glucose']]=(d[['Glucose']]-b2)/a2
# d[['BloodPressure']]=(d[['BloodPressure']]-b3)/a3
# d[['SkinThickness']]=(d[['SkinThickness']]-b4)/a4
# d[['Insulin']]=(d[['Insulin']]-b5)/a5
# d[['BMI']]=(d[['BMI']]-b6)/a6
# d[['DiabetesPedigreeFunction']]=(d[['DiabetesPedigreeFunction']]-b7)/a7
# d[['Age']]=(d[['Age']]-b8)/a8
data = data.values
x = data[:,:-1]
y = data[:,8:9]
x = StandardScaler().fit_transform(x) # this function can also do mean scaling
x=torch.from_numpy(x)
y=torch.from_numpy(y)
x=x.float()
y=y.float()
print(x,y)

tensor([[ 0.6399,  0.8483,  0.1496,  ...,  0.2040,  0.4685,  1.4260],
        [-0.8449, -1.1234, -0.1605,  ..., -0.6844, -0.3651, -0.1907],
        [ 1.2339,  1.9437, -0.2639,  ..., -1.1033,  0.6044, -0.1056],
        ...,
        [ 0.3430,  0.0033,  0.1496,  ..., -0.7352, -0.6852, -0.2758],
        [-0.8449,  0.1598, -0.4707,  ..., -0.2402, -0.3711,  1.1707],
        [-0.8449, -0.8730,  0.0462,  ..., -0.2021, -0.4738, -0.8714]]) tensor([[1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
      

In [153]:
data.shape

(768, 9)

In [154]:
X_train , X_test, Y_train , Y_test = train_test_split(x, y, test_size =0.2 , random_state = 42)

In [155]:
# Intialising weights and biases
w =  torch.rand((x.size()[1],1),requires_grad=True)
b = torch.rand(1,requires_grad=True)
w.shape,b.shape

(torch.Size([8, 1]), torch.Size([1]))

In [179]:
#sigmoid function
def sigmoid(x):
    """Sigmoid function that squashes the input between 0 and 1"""
    activation = torch.reciprocal(torch.add(1,torch.exp(torch.neg(x))))
    return activation

In [180]:
# logistic model
def model(x):
    #linear regression x * w^T + b
    linear_ =  torch.add(torch.matmul(x,w),b)
    # bound the output with sigmoid activation
    linear_activation =  sigmoid(linear_)
    return linear_activation

In [181]:
def bce_loss(y_true, y_pred):
    """binary_cross_entropy
    Loss function for the training of the logistic regression"""
    # lambda or 1/N in above figure
    lambda_ =  1/(y_true.size()[0])
    # epsilon is added to contents in log function, this is to prevent finding log of zero as sigmoid is always greater or equal to zero
    epsilon = 1e-10

    # calculate
    m1 = torch.mul(y_true,torch.log(torch.add(y_pred,epsilon)))
    m2 = torch.mul(torch.add(1,torch.neg(y_true)),torch.log(torch.add(1+epsilon,torch.neg(y_pred))))
    lm = torch.add(m1,m2)
    l_theta = torch.mul(torch.sum(lm),-lambda_)
    return l_theta

In [184]:
def fun(Y_pred):
    for i in range(Y_pred.shape[0]):
      if(Y_pred[i]>=0.5):
        print(1)
      else:
        print(0)

In [191]:
# check if your implementation is correct
Y_pred = model(X_train)

In [192]:
print(Y_pred)

tensor([[0.0111],
        [0.9717],
        [0.2468],
        [0.6618],
        [0.9378],
        [0.3370],
        [0.0277],
        [0.8939],
        [0.3551],
        [0.0621],
        [0.2261],
        [0.4863],
        [0.1948],
        [0.5685],
        [0.6615],
        [0.7446],
        [0.5980],
        [0.5408],
        [0.3086],
        [0.8943],
        [0.9730],
        [0.5736],
        [0.2946],
        [0.9290],
        [0.8503],
        [0.6260],
        [0.9600],
        [0.6764],
        [0.5810],
        [0.6005],
        [0.9070],
        [0.2724],
        [0.2495],
        [0.3138],
        [0.8856],
        [0.8777],
        [0.1551],
        [0.2125],
        [0.4045],
        [0.6356],
        [0.5524],
        [0.3282],
        [0.2404],
        [0.1413],
        [0.3803],
        [0.6794],
        [0.5416],
        [0.2983],
        [0.7715],
        [0.8853],
        [0.8098],
        [0.4038],
        [0.1785],
        [0.3988],
        [0.9144],
        [0

In [193]:
loss = bce_loss(Y_train,Y_pred)
print("initial loss",loss)

initial loss tensor(0.7219, grad_fn=<MulBackward0>)


In [194]:
Y_pred.shape

torch.Size([614, 1])

In [195]:
Y_train.shape

torch.Size([614, 1])

In [199]:
# Adjust weights & reset gradients
# Train for 10000 epochs

for i in range(10000):
    Y_pred =  model(X_train)
    loss =  bce_loss(Y_train,Y_pred)

    # calculate gradient w.r.t loss (backprop)
    loss.backward(retain_graph=True)
    w_grad = w.grad
    b_grad = b.grad
    learning_rate = 0.005
    with torch.no_grad():
        w -= torch.mul(learning_rate,w_grad)
        b -= torch.mul(learning_rate,b_grad)
        w.grad.zero_()
        b.grad.zero_()

    if i%1000 == 0:
      print(f"epoch {i} loss {loss.item()}")

epoch 0 loss 0.46783509850502014
epoch 1000 loss 0.46783509850502014
epoch 2000 loss 0.46783509850502014
epoch 3000 loss 0.46783503890037537
epoch 4000 loss 0.46783503890037537
epoch 5000 loss 0.46783503890037537
epoch 6000 loss 0.46783503890037537
epoch 7000 loss 0.467835009098053
epoch 8000 loss 0.46783503890037537
epoch 9000 loss 0.46783503890037537


In [200]:
loss = bce_loss(Y_train,Y_pred)
print("loss : ",loss)

loss :  tensor(0.4678, grad_fn=<MulBackward0>)


In [201]:
Y_test_pred = model(X_test)
loss = bce_loss(Y_test,Y_test_pred)
print("loss : ",loss)

loss :  tensor(0.5105, grad_fn=<MulBackward0>)


In [203]:
for i in range(Y_pred.shape[0]):
  if(Y_pred[i]>=0.5):
    Y_pred[i]=1.0
  else:
    Y_pred[i]=0.0

In [204]:
Y_pred

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [206]:
# using sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [207]:
df = pd.read_csv(r'/Users/freddy/Desktop/CSV_FILES/diabetes.csv')
x_np = df.iloc[:, :-1].values

# Standardize the data
x_norm = StandardScaler().fit_transform(x_np) # x-x_mean/max
x = torch.from_numpy(x_norm)
x = x.float()
y_np = df.iloc[:, -1].values
y = torch.from_numpy(y_np)
y = y.float().unsqueeze(1)

In [208]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.2)

In [211]:
model = linear_model.LogisticRegression()
model.fit(x_train,y_train.ravel())

LogisticRegression()

In [212]:
model.predict(x_test)

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0.], dtype=float32)

In [213]:
model.score(x_test,y_test)

0.7532467532467533

In [222]:
y_pred = model.predict(x_train)
loss = bce_loss(y_train,torch.tensor(y_pred))
print("loss : ",loss)

loss :  tensor(nan)


In [218]:
y_pred

(614,)

In [220]:
y_train.shape

torch.Size([614, 1])

In [233]:
y_pred1 = model.predict(x_test)
loss = bce_loss(y_test,torch.tensor(y_pred1))
print("loss : ",loss)

loss :  tensor(nan)


In [230]:
y_pred1 = torch.tensor(y_pred1).reshape(154,1)

In [238]:
y_test.shape

torch.Size([154, 1])

In [239]:
y_pred1.shape

(154,)

In [235]:
y_pred1

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0.], dtype=float32)

In [236]:
y_test

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
      

In [240]:
import tensorflow as tf

In [243]:
y_pred1 = tf.convert_to_tensor(y_pred1)

In [248]:
y_pred1 = y_pred1.reshape([154,1])

In [247]:
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()

In [251]:
y_pred1

<tf.Tensor: shape=(154, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
 

In [252]:
y_test

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
      

In [253]:
y_test.shape,y_pred1.shape

(torch.Size([154, 1]), TensorShape([154, 1]))